# Lab-01-1 Tensor Manipulation 1 (1)
# NumPy Review

In [1]:
import numpy as np

## 1D Array with NumPy

In [4]:
t = np.array([ 0., 1., 2., 3., 4., 5., 6., ])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [5]:
print("Rank of t: ", t.ndim)
print("Shape of t: ", t.shape)

Rank of t:  1
Shape of t:  (7,)


In [11]:
print("t[0] t[1] t[-1] = ", t[0], t[1], t[-1])  # Element
print("t[2:5] t[4:-1]  = ", t[2:5], t[4:-1])    # Slicing
print("t[:2] t[3:]     = ", t[:2], t[3:])       # Slicing

t[0] t[1] t[-1] =  [1. 2. 3.] [4. 5. 6.] [10. 11. 12.]
t[2:5] t[4:-1]  =  [[ 7.  8.  9.]
 [10. 11. 12.]] []
t[:2] t[3:]     =  [[1. 2. 3.]
 [4. 5. 6.]] [[10. 11. 12.]]


## 2D Array with NumPy

In [9]:
t = np.array([[1., 2., 3.], [4., 5., 6.,], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [10]:
print("Rank  of t: ", t.ndim)
print("Shape of t: ", t.shape)

Rank  of t:  2
Shape of t:  (4, 3)
