# Lab-01-2 Tensor Manipulation 2

In [1]:
import numpy as np
import torch

## View (Reshape in NumPy)

매우 중요함. shape를 내 생각대로 자유자재로 바꿀 수 있어야 함.

In [4]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
            
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)              # |ft| = (2, 2, 3)

torch.Size([2, 2, 3])


In [5]:
print(ft.view([-1, 3]))      # => (2x2, 3) = (4, 3)
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [7]:
print(ft.view([-1, 1, 3]))   # => (2x2, 1, 3) = (4, 1, 3) 
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze

view와 달리 squeeze에서는 자동으로 어떤 dimension의 element 수가 1인 경우에 그 dimension을 없애 준다.

`squeeze(dim=0)`을 하면 dimension 0에서 element가 1이면 dimension 없애 줌.

In [8]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [24]:
print(ft.squeeze())      # (3, 1) => (3,)
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze

`|ft| = (3,)`일 때 `dim=0`이면 `(1, 3)`, `dim=1`이면 `(3, 1)`.

In [11]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [12]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [13]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [14]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [15]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting

In [16]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [17]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [18]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [19]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## Concatenate

In [20]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [21]:
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking

In [27]:
# |x| = |y| = |z| = (2,)
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [25]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [28]:
# equivalent (x.unsqueeze(0) : (1, 2))
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros

In [30]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [31]:
print(torch.ones_like(x))    # same shape (size)
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


복잡한 모델을 이용하다 보면 같은 device (같은 CPU 코어, GPU라든가)에 있어야만 연산이 가능할 때가 있는데, `ones_like()`, `zeros_like()`을 쓰면 동일한 device 안에서 데이터를 생성해 줄 것. 

## In-place Operation

In [32]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [34]:
print(x.mul(2.))    # x x 2
print(x)
print(x.mul_(2.))   # x x 2 => _를 뒤에 달아주면 mutable. (새로운 텐서를 할당해 줄 필요가 없다.)
print(x)

tensor([[ 4.,  8.],
        [12., 16.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[ 4.,  8.],
        [12., 16.]])
tensor([[ 4.,  8.],
        [12., 16.]])


그러나, PyTorch는 가비지 컬렉터가 잘 작동하기 때문에, in-place 연산이 효율 측면에서 크게 이득을 주진 않을 수 있다고 공식에서는 설명하고 있음.